CHECK_EXISTING_NAME = "SELECT * FROM medios WHERE nombre = '%s'"
CHECK_EXISTING_URL = "SELECT * FROM medios WHERE url = '%s'"
CHECK_EXISTING_LOC = "SELECT * FROM ubicaciones WHERE ciudad = '%s' AND pais = '%s' AND region = '%s' AND continente = '%s'"
CHECK_EXISTING_FOUNDER = "SELECT * FROM datosFundadores WHERE nombre = '%s' AND apellido = '%s'"
INSERT_MEDIA_OUTLET = "INSERT INTO medios (nombre, ubicacion, año, url) VALUES ('%s', '%i', '%i', '%s')"
INSERT_MEDIA_OUTLET_WY = "INSERT INTO medios (nombre, ubicacion, url) VALUES ('%s', '%s', '%s')"
INSERT_MEDIA_OUTLET_WU = "INSERT INTO medios (nombre, año, url) VALUES ('%s', '%i', '%s')"
INSERT_MEDIA_OUTLET_WU_WY = "INSERT INTO medios (nombre, url) VALUES ('%s', '%s')"
INSERT_LOCATION = "INSERT INTO ubicaciones (ciudad, pais, region, continente) VALUES ('%s', '%s', '%s', '%s')"
INSERT_COVERAGE = "INSERT INTO coberturasMedios (medio, cobertura) VALUES ('%i', '%i')"
INSERT_EXAMPLE = "INSERT INTO ejemplos (medio, url, xpath_fecha, xpath_titulo, xpath_desc) VALUES ('%i', '%s', '%s', '%s', '%s')"
INSERT_NETWORK = "INSERT INTO redes (medio, red, cuenta, seguidores, updated) VALUES ('%i', '%i', '%s', '%i', NOW())"
INSERT_FOUNDER = "INSERT INTO datosFundadores (nombre, apellido, nacionalidad, dob) VALUES ('%s', '%s', '%s', '%s')"
INSERT_FOUNDER_WN = "INSERT INTO datosFundadores (nombre, apellido, dob) VALUES ('%s', '%s', '%s')"
INSERT_FOUNDER_WD = "INSERT INTO datosFundadores (nombre, apellido, nacionalidad) VALUES ('%s', '%s', '%s')"
INSERT_FOUNDER_WN_WD = "INSERT INTO datosFundadores (nombre, apellido) VALUES ('%s', '%s')"
INSERT_MEDIA_FOUNDERS = "INSERT INTO fundadoresMedios (medio, fundador) VALUES ('%i', '%i')"