CHECK_EXISTING_NAME = "SELECT * FROM medios WHERE nombre = '%s'"
CHECK_EXISTING_URL = "SELECT * FROM medios WHERE url = '%s'"
CHECK_EXISTING_LOC = "SELECT * FROM ubicaciones WHERE ciudad = '%s' AND pais = '%s' AND region = '%s' AND continente = '%s'"
CHECK_EXISTING_FOUNDER = "SELECT * FROM datosFundadores WHERE nombre = '%s' AND apellido = '%s'"
CHECK_EXISTING_CATEGORY = "SELECT * FROM datosCategorias WHERE nombre = '%s'"
INSERT_MEDIA_OUTLET = "INSERT INTO medios (nombre, ubicacion, año, url) VALUES ('%s', '%i', '%i', '%s')"
INSERT_MEDIA_OUTLET_WY = "INSERT INTO medios (nombre, ubicacion, url) VALUES ('%s', '%s', '%s')"
INSERT_MEDIA_OUTLET_WU = "INSERT INTO medios (nombre, año, url) VALUES ('%s', '%i', '%s')"
INSERT_MEDIA_OUTLET_WU_WY = "INSERT INTO medios (nombre, url) VALUES ('%s', '%s')"
INSERT_LOCATION = "INSERT INTO ubicaciones (ciudad, pais, region, continente) VALUES ('%s', '%s', '%s', '%s')"
INSERT_COVERAGE = "INSERT INTO coberturasMedios (medio, cobertura) VALUES ('%i', '%i')"
INSERT_EXAMPLE = "INSERT INTO ejemplos (medio, url, xpath_fecha, xpath_titulo, xpath_desc) VALUES ('%i', '%s', '%s', '%s', '%s')"
INSERT_NETWORK = "INSERT INTO redes (medio, red, cuenta, seguidores, updated) VALUES ('%i', '%i', '%s', '%i', NOW())"
INSERT_FOUNDER = "INSERT INTO datosFundadores (nombre, apellido, nacionalidad, dob) VALUES ('%s', '%s', '%s', '%s')"
INSERT_FOUNDER_WN = "INSERT INTO datosFundadores (nombre, apellido, dob) VALUES ('%s', '%s', '%s')"
INSERT_FOUNDER_WD = "INSERT INTO datosFundadores (nombre, apellido, nacionalidad) VALUES ('%s', '%s', '%s')"
INSERT_FOUNDER_WN_WD = "INSERT INTO datosFundadores (nombre, apellido) VALUES ('%s', '%s')"
INSERT_MEDIA_FOUNDERS = "INSERT INTO fundadoresMedios (medio, fundador) VALUES ('%i', '%i')"
INSERT_CATEGORY = "INSERT INTO datosCategorias (nombre) VALUES ('%s')"
INSERT_MEDIA_CATEGORY = "INSERT INTO categoriasMedios (medio, nombre, url, ejemplo, xpath) VALUES ('%i', '%i', '%s', '%s', '%s')"
XPATH_DATE = "SELECT xpath_fecha FROM ejemplos JOIN medios ON ejemplos.medio = medios.id WHERE medios.nombre = '%s'"
FOUNDERS = "SELECT f.nombre, f.apellido, f.nacionalidad FROM fundadoresMedios fm JOIN medios m ON fm.medio = m.id JOIN datosFundadores f ON f.id = fm.fundador WHERE m.nombre = '%s'"
CATEGORIES = "SELECT dc.nombre FROM datosCategorias dc JOIN categoriasMedios cm ON dc.id = cm.nombre JOIN medios m ON cm.medio = m.id WHERE m.nombre = '%s'"
NETWORKS = "SELECT dr.nombre, r.cuenta, r.seguidores FROM datosRedes dr JOIN redes r ON dr.id = r.red JOIN medios m ON r.medio = m.id WHERE m.nombre = '%s'"
COUNT_MEDIA_OUTLETS = "SELECT COUNT(*) FROM medios"
SUM_FOLLOWERS = "SELECT SUM(r.seguidores) FROM redes r JOIN medios m ON r.medio = m.id WHERE m.nombre = '%s'"
MEDIA_OUTLET_URL = "SELECT url FROM medios WHERE medios.nombre = '%s'"
LAST_UPDATE = "SELECT r.updated FROM datosRedes dr JOIN redes r ON dr.id = r.red JOIN medios m ON m.id = r.medio WHERE m.nombre = '%s' AND dr.nombre = '%s'"
COUNT_MEDIA_FOUNDERS = "SELECT COUNT(*) FROM fundadoresMedios fm JOIN datosFundadores df ON fm.fundador = df.id WHERE df.nombre = '%s' AND df.apellido = '%s'"
COUNT_MEDIA_LOCATIONS = "SELECT COUNT(*) FROM medios m JOIN ubicaciones u ON m.ubicacion = u.id WHERE u.ciudad = '%s' and u.pais = '%s'"
MEDIA_OVER_50K = "SELECT COUNT(*) FROM redes r JOIN datosRedes dr ON r.red = dr.id WHERE dr.nombre = '%s' AND r.seguidores >= 50000"
MEDIA_AVERAGE = "SELECT dr.nombre, AVG(r.seguidores) FROM datosRedes dr JOIN redes r ON dr.id = r.red GROUP BY dr.nombre"